### ISSUE TITLE
Pill-shaped buttons throughout site:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#42]
Can we give these a little more padding around the two sides of the text (minimum 20px). 

https://drive.google.com/file/d/17BFfIMeXIIgkCXVamphBwrLSs7v9OYNF/view?usp=sharing

It also looks like some of the yellow buttons are smaller than others. The only one that was designed shorter was the "download" button in the main nav. The rest of the yellow button should all have same height and corner treatment:

https://drive.google.com/file/d/17Zvc2CgsEIoLRvM6mhBXo28-csK0-VyI/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel16 Please review and close if all is good.  Thanks!

**Comment by jthiel16** [comment]
@cmoosman1 I'm still seeing the issue
cc @jtuckertw

**Comment by jtuckertw** [comment]
@jthiel16 Please revalidate and close if all is good.  Thanks!

**Comment by jthiel16** [comment]
@cmoosman1 I'm still seeing the issue. I like the vertical height of the "Submit" and "Contact Us" buttons near the footer, but the rest of the buttons on the page look a bit smaller and inconsistent

**Comment by cmoosman1** [comment]
@jthiel16 - So all the pill buttons are width - 220px(100%) height - 50px, No sure what you want to do here?

**Comment by jthiel16** [comment]
@cmoosman1 The height may be set to 50, but they're actually appearing at different size heights for whatever reason (different padding?). Here is a comparison of styles between the "Download Catalog" button and the "Submit" buttons on the bottom of home page:

<img width="222" alt="Screen Shot 2019-12-26 at 10 07 06 AM" src="https://user-images.githubusercontent.com/35710312/71484430-9af6d980-27c9-11ea-86e4-16ada850514a.png">
<img width="246" alt="Screen Shot 2019-12-26 at 10 06 46 AM" src="https://user-images.githubusercontent.com/35710312/71484518-09d43280-27ca-11ea-9b23-22261a6945a0.png">

What I'm looking for is to have the same consistent height and 25px corner radius. As example, right now on the home page, the two at the bottom (Submit and Contact Us) appear larger than the rest (Learn About Subsalve, Contact Us, See All Accessories, View All Case Studies, Go To Article, Download Catalog). I like the look/styles on the Submit/Contact Us buttons now.

<img width="1286" alt="Screen Shot 2019-12-26 at 10 27 17 AM" src="https://user-images.githubusercontent.com/35710312/71484583-56b80900-27ca-11ea-8db3-9b8f43f24365.png">

**Comment by cmoosman1** [comment]
@jthiel16 - I have all the buttons with the same width/height, I have messed with the padding and they are all visually the same width/height

**Comment by jthiel16** [comment]
Thanks @cmoosman1 that looks much better
